version: '3'
services: 
  rabbitmq-management:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend
networks:
  backend: 
    external:
      name: net